#Development Stage 
FROM node:22-alpine as dev

# Define working directory in container 
WORKDIR /app

#copy package.json and package.lock.json to container
COPY frontend/package.json ./
RUN npm install

# copy all files to container 
COPY frontend/ .

# start app in development stage
CMD [ "npm", "start" ]
# Build stage
FROM node:22-alpine as build

# Define working directory in container 
WORKDIR /app

#copy package.json and package.lock.json to container
COPY frontend/package.json ./
RUN npm install

# copy all files to container 
COPY frontend/ .

RUN npm run build 

# Production Stage
FROM nginx:alpine as prod
COPY  --from=build /app/build /usr/share/nginx/html

CMD [ "nginx", "-g" ,"daemon off;" ]
