#Development Stage 
 FROM node:22-alpine as dev

 # Define working directory in container 
 WORKDIR /app

 #copy package.json and package.lock.json to container
 COPY api/package.json ./
 RUN npm install

# copy all files to container 
COPY api/ .

CMD [ "npx" ,"nodemon", "server.js" ]

#production stage 
FROM node:22-alpine as prod

# Define working directory in container 
WORKDIR /app

#copy package.json and package.lock.json to container
COPY api/package.json ./
RUN npm install

# copy all files to container 
COPY api/ .

#Start app in Production stage
CMD [ "node", "server.js" ]

